name: Auto Commit and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # Questo farà eseguire il workflow ogni 10 minuti

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Add, commit, and push changes
        run: |
          git add .
          git commit -m "Auto commit delle modifiche da Obsidian"
          git push origin main
